# this file contains HTTP requests fot the REST Client extension of visual studio code
@url=http://localhost:8080/certificates

###
# request all certificate, will be empty if just started
GET {{url}}

###
# POST github certificate to the service
# @name github
POST {{url}}
Content-Type: text/plain

< ./github.com.crt

###
# store the returned id field from the response in a variable for further reference
@githubId = {{github.response.body.$.id}}
GET {{url}}/{{githubId}}

###
# POST google certificate to the service
# @name google
POST {{url}}
Content-Type: text/plain

< ./google.com.crt

###
# store the returned id field from the response in a variable for further reference
@googleId = {{google.response.body.$.id}}
GET {{url}}/{{googleId}}

###
# POST microsoft certificate to the service
# @name microsoft
POST {{url}}
Content-Type: text/plain

< ./www.microsoft.com.crt

###
# store the returned id field from the response in a variable for further reference
@microsoftId = {{microsoft.response.body.$.id}}
GET {{url}}/{{microsoftId}}

###
# search for certificates with microsoft.com in the subject DN
GET {{url}}?subject=microsoft.com
###
# search for certificates with privacy.microsoft.com in the DNS names in subject alternative names
GET {{url}}?dns=privacy.microsoft.com
###
# search for certificates with www.github.com in the DNS names in subject alternative names
GET {{url}}?dns=www.github.com
###
# get all certificates as CSV list
GET {{url}}
Accept: text/csv
###
###
# get a CSV list with all certificates expiring within the coming 365 days, sorted by expiration date
GET {{url}}?expiring=P365D
Accept: text/csv
###